# This test builds all containers and runs some smoke tests
# in a fully containerized version
name: Test containerized (no LM)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          architecture: x64
          activate-environment: swe-agent
          environment-file: environment.yml
      - name: Run setup and create keys.cfg
        run: |
          ./setup.sh
          touch keys.cfg
        shell: bash
      - name: Build swe-agent-run container
        run: |
          docker build -t sweagent/swe-agent-run:latest .
      - name: Show docker images
        run: |
          docker image ls
      - name: Run pytest
        run: |
          docker run -it sweagent/swe-agent-run:latest  /bin/bash -c "pip install pytest && pytest -k test_replay" 